# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0005_character_gold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(choices=[(20, 'Small'), (40, 'Medium'), (60, 'Long')], default=20, help_text='Mission duration in minutes', verbose_name='Mission duriation')),
                ('reward', models.IntegerField(blank=True, help_text='Reward for mission', null=True, verbose_name='Reward')),
                ('started', models.DateTimeField(default=django.utils.timezone.now, help_text='Started time', verbose_name='Started time')),
                ('character', models.ForeignKey(help_text='Character assigned to mission', on_delete=django.db.models.deletion.CASCADE, to='character.Character', verbose_name='Character')),
            ],
        ),
    ]
